apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: tanvishinde017/flask-k8s-app:latest   # ✅ added tag
        imagePullPolicy: Always                      # ✅ always pull latest
        ports:
        - containerPort: 5000

        resources:                                   # ✅ needed for auto scaling
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"